import type{Metadata}from"next";
import{hasLocale}from"next-intl";
import{getTranslations,setRequestLocale}from"next-intl/server";
import{notFound}from"next/navigation";
import{Container}from"@/components/layout/container";
import{RegexTester,type RegexTesterLabels}from"@/components/tools/regex-tester/regex-tester";
import{routing}from"@/i18n/routing";
import{createPageMetadata}from"@/lib/seo";
type Props={params:Promise<{locale:string}>};
export async function generateMetadata({params}:Props):Promise<Metadata>{const{locale}=await params;if(!hasLocale(routing.locales,locale))notFound();const t=await getTranslations({locale,namespace:"Tools.regexTester.metadata"});return createPageMetadata({locale,title:t("title"),description:t("description"),pathname:`/${locale}/tools/regex-tester`});}
export default async function Page({params}:Props){const{locale}=await params;if(!hasLocale(routing.locales,locale))notFound();setRequestLocale(locale);const t=await getTranslations("Tools.regexTester");const labels:RegexTesterLabels={pattern:t("fields.pattern"),patternHelp:t("fields.patternHelp"),flags:t("fields.flags"),flagDescriptions:{g:t("flags.g"),i:t("flags.i"),m:t("flags.m"),s:t("flags.s"),u:t("flags.u"),y:t("flags.y")},test:t("fields.test"),testHelp:t("fields.testHelp"),replacement:t("fields.replacement"),replacementHelp:t("fields.replacementHelp"),valid:t("status.valid"),running:t("status.running"),noMatch:t("status.noMatch"),matches:t("status.matches"),firstOnly:t("status.firstOnly"),global:t("status.global"),preview:t("preview.title"),previewEmpty:t("preview.empty"),details:t("details.title"),detailsEmpty:t("details.empty"),value:t("details.value"),index:t("details.index"),groups:t("details.groups"),namedGroups:t("details.named"),unmatched:t("details.unmatched"),zeroLength:t("details.zero"),truncated:t("details.truncated"),detailsTruncated:t("details.detailLimit"),highlightTruncated:t("preview.limit"),replacePreview:t("replace.title"),unchanged:t("replace.unchanged"),run:t("actions.run"),clear:t("actions.clear"),copyPattern:t("actions.copyPattern"),copyLiteral:t("actions.copyLiteral"),copyReplacement:t("actions.copyReplacement"),copied:t("actions.copied"),examples:t("examples.title"),exampleHint:t("examples.hint"),exampleLabels:{email:t("examples.email"),number:t("examples.number"),date:t("examples.date"),url:t("examples.url"),phone:t("examples.phone")},errors:{"pattern-too-long":t("errors.patternLong"),"text-too-long":t("errors.textLong"),"replacement-too-long":t("errors.replacementLong"),"replacement-too-large":t("errors.resultLarge"),"regex-timeout":t("errors.timeout"),"worker-error":t("errors.worker"),"copy-failed":t("errors.copy")},batch:{title:t("batch.title"),help:t("batch.help"),addRow:t("batch.addRow"),removeRow:t("batch.removeRow"),placeholder:t("batch.placeholder"),matched:t("batch.matched"),notMatched:t("batch.notMatched"),matchCount:t.raw("batch.matchCount"),captures:t("batch.captures"),timeout:t("batch.timeout"),empty:t("batch.empty")}};
return <><section className="border-b border-[var(--border)] bg-[var(--surface)]"><Container className="py-10 sm:py-14"><div className="max-w-4xl"><h1 className="text-3xl font-bold tracking-tight sm:text-5xl">{t("title")}</h1><p className="mt-4 text-lg leading-8 text-[var(--text-muted)]">{t("description")}</p></div></Container></section><Container className="py-8 sm:py-12"><RegexTester labels={labels}/><section className="mt-8 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5 sm:p-6"><h2 className="text-xl font-bold">{t("reference.title")}</h2><p className="mt-2 text-sm text-[var(--text-muted)]">{t("reference.description")}</p><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{["characters","quantifiers","anchors","groups","lookaround","escape"].map(key=><div key={key} className="rounded-xl bg-[var(--surface-muted)] p-4"><h3 className="font-bold">{t(`reference.${key}.title`)}</h3><code className="mt-2 block whitespace-pre-wrap text-sm leading-6 text-[var(--foreground)]">{t(`reference.${key}.items`)}</code></div>)}</div></section><p className="mt-6 rounded-xl bg-[var(--info-bg)] p-4 text-sm leading-6 text-[var(--info-fg)]">{t("privacy")}</p></Container></>}
