import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import { Base64Converter, type Base64ConverterLabels } from "./base64-converter";

const labels:Base64ConverterLabels={modeLabel:"Mode",encodeMode:"Encode mode",decodeMode:"Decode mode",encodingLabel:"Encoding",encodingHelp:"Help",encodings:{auto:"Auto","utf-8":"UTF-8","utf-16le":"UTF-16LE","utf-16be":"UTF-16BE",ascii:"ASCII","iso-8859-1":"ISO","windows-1252":"Windows", "euc-kr":"EUC-KR",shift_jis:"Shift_JIS"},inputEncode:"Plain input",inputDecode:"Base64 input",inputPlaceholderEncode:"text",inputPlaceholderDecode:"base64",resultEncode:"Base64 result",resultDecode:"Decoded result",resultEmpty:"empty",encode:"Encode",decode:"Decode",clear:"Clear",copy:"Copy",copied:"Copied",converting:"Converting",applied:"Applied {encoding}",autoUsed:"Auto UTF-8",autoBom:"BOM {encoding}",autoEstimated:"Estimated {encoding}",autoLow:"Low {encoding}",errors:{base64:"Invalid Base64",unrepresentable:"Cannot represent","invalid-bytes":"Invalid bytes",ambiguous:"Ambiguous",load:"Load failed",copy:"Copy failed"}};
afterEach(()=>vi.restoreAllMocks());
function result(){return screen.getByRole("textbox",{name:/result/i}) as HTMLTextAreaElement;}

describe("Base64Converter",()=>{
  it("has the specified empty initial state",()=>{render(<Base64Converter labels={labels}/>);expect(screen.getByText("Auto UTF-8")).toBeTruthy();expect((screen.getByRole("button",{name:"Encode"}) as HTMLButtonElement).disabled).toBe(true);expect((screen.getByRole("button",{name:"Copy"}) as HTMLButtonElement).disabled).toBe(true);});
  it("encodes Unicode with Auto UTF-8 and clears on mode change",async()=>{render(<Base64Converter labels={labels}/>);fireEvent.change(screen.getByRole("textbox",{name:"Plain input"}),{target:{value:"한글😀"}});fireEvent.click(screen.getByRole("button",{name:"Encode"}));await waitFor(()=>expect(result().value).not.toBe(""));fireEvent.click(screen.getByRole("button",{name:"Decode mode"}));expect((screen.getByRole("textbox",{name:"Base64 input"}) as HTMLTextAreaElement).value).toBe("");expect(result().value).toBe("");});
  it("shows friendly invalid Base64 and clears it on edit",async()=>{render(<Base64Converter labels={labels}/>);fireEvent.click(screen.getByRole("button",{name:"Decode mode"}));const input=screen.getByRole("textbox",{name:"Base64 input"});fireEvent.change(input,{target:{value:"%%%"}});fireEvent.click(screen.getByRole("button",{name:"Decode"}));expect(await screen.findByRole("alert")).toHaveProperty("textContent","Invalid Base64");fireEvent.change(input,{target:{value:"QQ=="}});expect(screen.queryByRole("alert")).toBeNull();});
  it("rejects unrepresentable input and preserves it",async()=>{render(<Base64Converter labels={labels}/>);fireEvent.change(screen.getByRole("combobox",{name:"Encoding"}),{target:{value:"ascii"}});const input=screen.getByRole("textbox",{name:"Plain input"}) as HTMLTextAreaElement;fireEvent.change(input,{target:{value:"한글"}});fireEvent.click(screen.getByRole("button",{name:"Encode"}));expect(await screen.findByRole("alert")).toHaveProperty("textContent","Cannot represent");expect(input.value).toBe("한글");});
  it("clears and focuses input",()=>{render(<Base64Converter labels={labels}/>);const input=screen.getByRole("textbox",{name:"Plain input"}) as HTMLTextAreaElement;fireEvent.change(input,{target:{value:"abc"}});fireEvent.click(screen.getByRole("button",{name:"Clear"}));expect(input.value).toBe("");expect(document.activeElement).toBe(input);});
  it("copies exactly and handles rejection",async()=>{const writeText=vi.fn().mockResolvedValue(undefined);Object.defineProperty(navigator,"clipboard",{configurable:true,value:{writeText}});render(<Base64Converter labels={labels}/>);fireEvent.change(screen.getByRole("textbox",{name:"Plain input"}),{target:{value:"A"}});fireEvent.click(screen.getByRole("button",{name:"Encode"}));await waitFor(()=>expect(result().value).toBe("QQ=="));fireEvent.click(screen.getByRole("button",{name:"Copy"}));await waitFor(()=>expect(writeText).toHaveBeenCalledWith("QQ=="));writeText.mockRejectedValueOnce(new Error("denied"));fireEvent.click(screen.getByRole("button",{name:"Copy"}));expect(await screen.findByRole("alert")).toHaveProperty("textContent","Copy failed");expect(result().value).toBe("QQ==");});
});
