import type { Metadata } from "next";
import { hasLocale } from "next-intl";
import { getTranslations, setRequestLocale } from "next-intl/server";
import { notFound } from "next/navigation";
import { Container } from "@/components/layout/container";
import { ImageCompressor, type ImageCompressorLabels } from "@/components/tools/image-compressor/image-compressor";
import { routing } from "@/i18n/routing";
import { createPageMetadata } from "@/lib/seo";
type PageProps={params:Promise<{locale:string}>};
export async function generateMetadata({params}:PageProps):Promise<Metadata>{const{locale}=await params;if(!hasLocale(routing.locales,locale))notFound();const t=await getTranslations({locale,namespace:"Tools.imageCompressor.metadata"});return createPageMetadata({locale,title:t("title"),description:t("description"),pathname:`/${locale}/tools/image-compressor`});}
export default async function Page({params}:PageProps){const{locale}=await params;if(!hasLocale(routing.locales,locale))notFound();setRequestLocale(locale);const t=await getTranslations("Tools.imageCompressor");
 const labels:ImageCompressorLabels={uploadTitle:t("upload.title"),uploadHelp:t("upload.help"),drop:t("upload.drop"),choose:t("actions.choose"),change:t("actions.change"),clear:t("actions.clear"),privacy:t("privacy.notice"),loading:t("status.loading"),compressing:t("status.compressing"),progress:t("status.progress"),compress:t("actions.compress"),download:t("actions.download"),infoTitle:t("info.title"),fileName:t("info.name"),format:t("info.format"),dimensions:t("info.dimensions"),size:t("info.size"),settings:t("settings.title"),mode:t("settings.mode"),qualityMode:t("settings.qualityMode"),targetMode:t("settings.targetMode"),quality:t("settings.quality"),target:t("settings.target"),customTarget:t("settings.customTarget"),output:t("settings.output"),original:t("settings.original"),maxWidth:t("settings.maxWidth"),keepSize:t("settings.keepSize"),pngNotice:t("notices.png"),jpegNotice:t("notices.jpeg"),metadataNotice:t("notices.metadata"),previewOriginal:t("preview.original"),previewResult:t("preview.result"),resultEmpty:t("preview.empty"),resultTitle:t("result.title"),resultSize:t("result.size"),saved:t("result.saved"),saving:t("result.saving"),larger:t("result.larger"),same:t("result.same"),targetMet:t("result.targetMet"),targetMissed:t("result.targetMissed"),actualQuality:t("result.quality"),formats:{jpeg:t("formats.jpeg"),png:t("formats.png"),webp:t("formats.webp")},errors:{"multiple-files":t("errors.multiple"),"unsupported-format":t("errors.unsupported"),"file-too-large":t("errors.fileLarge"),"signature-mismatch":t("errors.signature"),"decode-failed":t("errors.decode"),"invalid-dimensions":t("errors.dimensions"),"encoder-unsupported":t("errors.encoder"),"encode-failed":t("errors.encode"),"target-invalid":t("errors.target"),"target-unreachable":t("errors.unreachable"),"download-failed":t("errors.download")}};
 return <><section className="border-b border-[var(--border)] bg-[var(--surface)]"><Container className="py-10 sm:py-14"><div className="max-w-3xl"><h1 className="text-3xl font-bold tracking-tight text-[var(--foreground)] sm:text-5xl">{t("title")}</h1><p className="mt-4 text-lg leading-8 text-[var(--text-muted)]">{t("description")}</p></div></Container></section><Container className="py-8 sm:py-12"><ImageCompressor labels={labels}/><section className="mt-8 grid gap-4 md:grid-cols-3"><Info title={t("guide.qualityTitle")} text={t("guide.qualityText")}/><Info title={t("guide.targetTitle")} text={t("guide.targetText")}/><Info title={t("privacy.title")} text={t("privacy.text")} blue/></section></Container></>}
function Info({title,text,blue=false}:{title:string;text:string;blue?:boolean}){return <div className={`rounded-2xl border p-5 ${blue?"border-[var(--info-border)] bg-[var(--info-bg)]":"border-[var(--border)] bg-[var(--surface)]"}`}><h2 className="font-bold">{title}</h2><p className="mt-2 text-sm leading-6 text-[var(--text-muted)]">{text}</p></div>}
