import type { Metadata } from "next";
import { hasLocale } from "next-intl";
import { getTranslations, setRequestLocale } from "next-intl/server";
import { notFound } from "next/navigation";
import { Container } from "@/components/layout/container";
import { ImageCompressor, type ImageCompressorLabels } from "@/components/tools/image-compressor/image-compressor";
import { InlineShareBar } from "@/components/layout/share-bar";
import { ToolDetailContent } from "@/components/tools/shared/tool-detail-content";
import { ToolPageHero } from "@/components/tools/shared/tool-page-hero";
import { routing } from "@/i18n/routing";
import { createPageMetadata } from "@/lib/seo";
type PageProps={params:Promise<{locale:string}>};
export async function generateMetadata({params}:PageProps):Promise<Metadata>{const{locale}=await params;if(!hasLocale(routing.locales,locale))notFound();const t=await getTranslations({locale,namespace:"Tools.imageCompressor.metadata"});return createPageMetadata({locale,title:t("title"),description:t("description"),pathname:`/${locale}/tools/image-compressor`});}
export default async function Page({params}:PageProps){const{locale}=await params;if(!hasLocale(routing.locales,locale))notFound();setRequestLocale(locale);const t=await getTranslations("Tools.imageCompressor");
 const common=await getTranslations("Common");
 const labels:ImageCompressorLabels={uploadTitle:t("upload.title"),uploadHelp:t("upload.help"),drop:t("upload.drop"),choose:t("actions.choose"),change:t("actions.change"),clear:t("actions.clear"),privacy:t("privacy.notice"),loading:t("status.loading"),compressing:t("status.compressing"),progress:t("status.progress"),compress:t("actions.compress"),download:t("actions.download"),infoTitle:t("info.title"),fileName:t("info.name"),format:t("info.format"),dimensions:t("info.dimensions"),size:t("info.size"),settings:t("settings.title"),mode:t("settings.mode"),qualityMode:t("settings.qualityMode"),targetMode:t("settings.targetMode"),quality:t("settings.quality"),target:t("settings.target"),customTarget:t("settings.customTarget"),output:t("settings.output"),original:t("settings.original"),maxWidth:t("settings.maxWidth"),keepSize:t("settings.keepSize"),pngNotice:t("notices.png"),jpegNotice:t("notices.jpeg"),metadataNotice:t("notices.metadata"),previewOriginal:t("preview.original"),previewResult:t("preview.result"),resultEmpty:t("preview.empty"),resultTitle:t("result.title"),resultSize:t("result.size"),saved:t("result.saved"),saving:t("result.saving"),larger:t("result.larger"),same:t("result.same"),targetMet:t("result.targetMet"),targetMissed:t("result.targetMissed"),actualQuality:t("result.quality"),formats:{jpeg:t("formats.jpeg"),png:t("formats.png"),webp:t("formats.webp")},errors:{"multiple-files":t("errors.multiple"),"unsupported-format":t("errors.unsupported"),"file-too-large":t("errors.fileLarge"),"signature-mismatch":t("errors.signature"),"decode-failed":t("errors.decode"),"invalid-dimensions":t("errors.dimensions"),"encoder-unsupported":t("errors.encoder"),"encode-failed":t("errors.encode"),"target-invalid":t("errors.target"),"target-unreachable":t("errors.unreachable"),"download-failed":t("errors.download"),"too-many-files":t("errors.tooManyFiles"),"zip-failed":t("errors.zipFailed")},
 batch:{tabSingle:t("batch.tabSingle"),tabBatch:t("batch.tabBatch"),title:t("batch.title"),help:t("batch.help"),choose:t("batch.choose"),reselect:t("batch.reselect"),clear:t("batch.clear"),columnFile:t("batch.columnFile"),columnSize:t("batch.columnSize"),columnStatus:t("batch.columnStatus"),columnResult:t("batch.columnResult"),statusPending:t("batch.statusPending"),statusProcessing:t("batch.statusProcessing"),statusDone:t("batch.statusDone"),statusError:t("batch.statusError"),run:t("batch.run"),running:t("batch.running"),downloadZip:t("batch.downloadZip"),zipping:t("batch.zipping"),summary:t("batch.summary")}};
 return <><ToolPageHero locale={locale} title={t("title")} description={t("description")} homeLabel={common("homeLabel")} category={{key:"image",label:common("toolsNav.categories.image")}} tool={{path:"/tools/image-compressor",label:t("title")}}/><Container className="py-8 sm:py-12"><ImageCompressor labels={labels}/><InlineShareBar/><ToolDetailContent toolPath="/tools/image-compressor" locale={locale}/></Container></>}
