import type{Metadata}from"next";
import{hasLocale}from"next-intl";
import{getTranslations,setRequestLocale}from"next-intl/server";
import{notFound}from"next/navigation";
import{Container}from"@/components/layout/container";
import{CronExpressionGenerator}from"@/components/tools/cron-expression-generator/cron-expression-generator";
import{routing}from"@/i18n/routing";
import{createPageMetadata}from"@/lib/seo";
type Props={params:Promise<{locale:string}>};
export async function generateMetadata({params}:Props):Promise<Metadata>{const{locale}=await params;if(!hasLocale(routing.locales,locale))notFound();const t=await getTranslations({locale,namespace:"Tools.cronExpressionGenerator.metadata"});return createPageMetadata({locale,title:t("title"),description:t("description"),pathname:`/${locale}/tools/cron-expression-generator`});}
export default async function Page({params}:Props){const{locale}=await params;if(!hasLocale(routing.locales,locale))notFound();setRequestLocale(locale);const t=await getTranslations("Tools.cronExpressionGenerator");return <><section className="border-b border-[var(--border)] bg-[var(--surface)]"><Container className="py-10 sm:py-14"><div className="max-w-3xl"><h1 className="text-3xl font-bold tracking-tight sm:text-5xl">{t("title")}</h1><p className="mt-4 text-lg leading-8 text-[var(--text-muted)]">{t("description")}</p></div></Container></section><Container className="py-8 sm:py-12"><CronExpressionGenerator/><section className="mt-8 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5 sm:p-6"><h2 className="text-xl font-bold">{t("reference.title")}</h2><p className="mt-2 text-[var(--text-muted)]">{t("reference.description")}</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><code className="rounded-xl bg-[var(--surface-muted)] p-4 whitespace-pre-wrap">{t("reference.syntax")}</code><div className="rounded-xl bg-[var(--surface-muted)] p-4 text-sm leading-7">{t("reference.fields")}</div></div><h2 className="mt-7 text-xl font-bold">{t("vercel.title")}</h2><p className="mt-2 leading-7 text-[var(--text-muted)]">{t("vercel.description")}</p></section><p className="mt-6 rounded-xl bg-[var(--info-bg)] p-4 text-sm leading-6 text-[var(--info-fg)]">{t("privacy")}</p></Container></>}
