import type { Metadata } from "next";
import Image from "next/image";
import { hasLocale } from "next-intl";
import { getTranslations, setRequestLocale } from "next-intl/server";
import { notFound } from "next/navigation";
import { Check, Link2, QrCode, Send, ServerOff } from "lucide-react";
import { Container } from "@/components/layout/container";
import { P2PFileTransfer } from "@/components/tools/p2p-file-transfer/p2p-file-transfer";
import { routing } from "@/i18n/routing";
import { createPageMetadata } from "@/lib/seo";

type PageProps = { params: Promise<{ locale: string }> };
export async function generateMetadata({ params }: PageProps): Promise<Metadata> { const { locale } = await params; if (!hasLocale(routing.locales, locale)) notFound(); const t = await getTranslations({ locale, namespace: "Tools.p2pFileTransfer.metadata" }); return createPageMetadata({ locale, title: t("title"), description: t("description"), pathname: `/${locale}/tools/p2p-file-transfer` }); }
export default async function Page({ params }: PageProps) { const { locale } = await params; if (!hasLocale(routing.locales, locale)) notFound(); setRequestLocale(locale); const t = await getTranslations("Tools.p2pFileTransfer"); const steps = ["select", "share", "connect", "transfer"] as const; const icons = [Send, QrCode, Link2, Check];
  return <><section className="border-b border-[var(--border)] bg-[var(--surface)]"><Container className="py-10 sm:py-14"><div className="max-w-4xl"><div className="flex flex-wrap gap-2">{["badgeStorage","badgeShare","badgeBrowser"].map(key => <span key={key} className="rounded-full bg-[var(--info-bg)] px-3 py-1 text-sm font-bold text-[var(--info-fg)]">{t(key)}</span>)}</div><h1 className="mt-5 text-3xl font-bold tracking-tight sm:text-5xl">{t("title")}</h1><p className="mt-4 text-lg leading-8 text-[var(--text-muted)]">{t("description")}</p></div></Container></section><Container className="py-8 sm:py-12"><P2PFileTransfer/>
    <section className="mt-12" aria-labelledby="how-title"><h2 id="how-title" className="text-2xl font-bold">{t("howTitle")}</h2><div className="mt-5 overflow-hidden rounded-3xl border border-[var(--border)] bg-[var(--surface)]"><Image src="/assets/p2p-file-transfer/how-it-works.svg" width={960} height={420} alt="" className="h-auto w-full"/><ol className="grid gap-0 border-t border-[var(--border)] sm:grid-cols-2 lg:grid-cols-4">{steps.map((step,index) => { const Icon=icons[index]; return <li key={step} className="p-5"><Icon aria-hidden className="text-[var(--primary)]"/><strong className="mt-3 block">{index+1}. {t(`steps.${step}.title`)}</strong><p className="mt-1 text-sm leading-6 text-[var(--text-muted)]">{t(`steps.${step}.text`)}</p></li>; })}</ol></div></section>
    <section className="mt-12 rounded-3xl border border-[var(--border)] bg-[var(--surface)] p-5 sm:p-8"><h2 className="text-2xl font-bold">{t("exampleTitle")}</h2><p className="mt-2 text-[var(--text-muted)]">{t("exampleText")}</p><div className="mt-6 grid gap-4 md:grid-cols-2"><Mock title={t("sender")} status={t("exampleSender")}/><Mock title={t("receiver")} status={t("exampleReceiver")}/></div></section>
    <section className="mt-12 grid gap-4 md:grid-cols-2"><Info title={t("privacyTitle")} text={t("privacyText")} icon={ServerOff}/><Info title={t("encryptionTitle")} text={t("encryptionText")} icon={Check}/></section>
    <section className="mt-12"><h2 className="text-2xl font-bold">{t("faqTitle")}</h2><div className="mt-4 space-y-3">{["upload","offline","complete","large","multiple","encrypted"].map(key => <details key={key} className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><summary className="cursor-pointer font-bold">{t(`faq.${key}.q`)}</summary><p className="mt-3 leading-7 text-[var(--text-muted)]">{t(`faq.${key}.a`)}</p></details>)}</div></section>
  </Container></>; }
function Mock({ title,status }:{title:string;status:string}){return <div className="rounded-2xl bg-[var(--surface-muted)] p-5"><strong>{title}</strong><div className="mt-4 rounded-xl bg-[var(--surface)] p-4"><div className="font-bold">vacation.mp4</div><div className="text-sm text-[var(--text-muted)]">2.0 GiB</div><div className="mt-4 h-3 overflow-hidden rounded-full bg-[var(--border)]"><div className="h-full w-[68%] bg-[var(--primary)]"/></div><div className="mt-2 text-sm font-semibold">68% · {status}</div></div></div>}
function Info({title,text,icon:Icon}:{title:string;text:string;icon:typeof Check}){return <div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6"><Icon aria-hidden className="text-[var(--primary)]"/><h2 className="mt-3 text-xl font-bold">{title}</h2><p className="mt-2 leading-7 text-[var(--text-muted)]">{text}</p></div>}
