"use client";
import{useEffect,useMemo,useState}from"react";
import{Check,Clipboard,RotateCcw}from"lucide-react";
import{useLocale,useTranslations}from"next-intl";
import{Button}from"@/components/ui/button";
import{DEFAULT_SETTINGS,FIELD_DEFINITIONS,PRESETS,describeCron,formatRun,generateCron,getBrowserTimeZone,nextRuns,settingsFromCron,validateCron,type CronError,type DescriptionLabels,type GeneratorMode,type GeneratorSettings}from"@/lib/tools/cron-expression-generator/cron";

const MODES:GeneratorMode[]=["every-minute","every-n-minutes","hourly","every-n-hours","daily","weekly","monthly","specific-date"];
const PRESET_KEYS=["everyMinute","every5Minutes","every10Minutes","every30Minutes","hourly","midnight","daily9","monday9","monthlyFirst","weekdays9"] as const;
const WEEKDAYS=[0,1,2,3,4,5,6],MONTHS=Array.from({length:12},(_,i)=>i+1),DATES=Array.from({length:31},(_,i)=>i+1);

export function CronExpressionGenerator(){const t=useTranslations("Tools.cronExpressionGenerator");const locale=useLocale();const[tab,setTab]=useState<"generator"|"direct">("generator");const[expression,setExpression]=useState("* * * * *");const[settings,setSettings]=useState<GeneratorSettings>(DEFAULT_SETTINGS);const[result,setResult]=useState(()=>validateCron(expression));const[zone,setZone]=useState("UTC");const[browserZone,setBrowserZone]=useState("UTC");const[count,setCount]=useState(5);const[ready,setReady]=useState(false);const[copied,setCopied]=useState<"cron"|"description"|null>(null);const[copyError,setCopyError]=useState(false);
 useEffect(()=>{const timer=setTimeout(()=>{const detected=getBrowserTimeZone();setBrowserZone(detected);setZone(detected);setReady(true)},0);return()=>clearTimeout(timer)},[]);
 useEffect(()=>{const timer=setTimeout(()=>setResult(validateCron(expression)),300);return()=>clearTimeout(timer)},[expression]);
 const descriptionLabels=useMemo<DescriptionLabels>(()=>({everyMinute:t("descriptions.everyMinute"),everyNMinutes:n=>t("descriptions.everyNMinutes",{n}),hourlyAt:m=>t("descriptions.hourlyAt",{m}),everyNHours:(n,m)=>t("descriptions.everyNHours",{n,m}),dailyAt:time=>t("descriptions.dailyAt",{time}),weeklyAt:(days,time)=>t("descriptions.weeklyAt",{days,time}),monthlyAt:(dates,time)=>t("descriptions.monthlyAt",{dates,time}),specificDate:(months,dates,time)=>t("descriptions.specificDate",{months,dates,time}),custom:t("descriptions.custom"),orSuffix:t("descriptions.orSuffix"),weekdays:WEEKDAYS.map(day=>t(`weekdayNames.${day}`))}),[t]);
 const description=result.valid?describeCron(result,descriptionLabels):"";const runs=useMemo(()=>{if(!ready||!result.valid)return[];try{return nextRuns(result.normalized,zone,count)}catch{return[]}},[ready,result,zone,count]);
 function applySettings(next:GeneratorSettings){setSettings(next);setExpression(generateCron(next));setTab("generator")}
 function applyMode(mode:GeneratorMode){applySettings({...settings,mode})}
 function directChange(value:string){setExpression(value);const parsed=validateCron(value);if(parsed.valid){const inferred=settingsFromCron(parsed);if(inferred)setSettings(inferred);else setSettings(current=>({...current,mode:"custom"}))}}
 function toggleList(key:"days"|"months"|"dates",value:number){const current=settings[key],next=current.includes(value)?current.filter(item=>item!==value):[...current,value];if(!next.length)return;applySettings({...settings,[key]:next})}
 function numeric(key:"minute"|"hour"|"interval",raw:string,min:number,max:number){const value=Math.min(max,Math.max(min,Number(raw)||min));applySettings({...settings,[key]:value})}
 async function copy(kind:"cron"|"description",value:string){try{await navigator.clipboard.writeText(value);setCopied(kind);setCopyError(false);setTimeout(()=>setCopied(null),1500)}catch{setCopyError(true)}}
 function clear(){setTab("generator");setSettings(DEFAULT_SETTINGS);setExpression("* * * * *");setResult(validateCron("* * * * *"));setZone(browserZone);setCount(5);setCopied(null);setCopyError(false)}
 const error=!result.valid&&!result.empty?formatError(result.error,t):null;
 return <div className="space-y-6">
  <section className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5 shadow-sm sm:p-6">
   <div role="tablist" aria-label={t("mode.label")} className="grid grid-cols-2 gap-2 rounded-xl bg-[var(--surface-muted)] p-1"><button role="tab" aria-selected={tab==="generator"} onClick={()=>setTab("generator")} className={tabClass(tab==="generator")}>{t("mode.generator")}</button><button role="tab" aria-selected={tab==="direct"} onClick={()=>setTab("direct")} className={tabClass(tab==="direct")}>{t("mode.direct")}</button></div>
   <div className="mt-6"><h2 className="text-lg font-bold">{t("presets.title")}</h2><div className="mt-3 flex flex-wrap gap-2">{PRESETS.map((preset,index)=><button key={preset} type="button" onClick={()=>{directChange(preset);setTab("generator")}} className="min-h-11 rounded-xl border border-[var(--border)] px-3 py-2 text-sm font-semibold hover:bg-[var(--surface-muted)]">{t(`presets.${PRESET_KEYS[index]}`)}</button>)}</div></div>
   {tab==="generator"?<div className="mt-6 space-y-5"><label className="block font-bold" htmlFor="cron-frequency">{t("generator.frequency")}</label><select id="cron-frequency" value={settings.mode} onChange={e=>applyMode(e.target.value as GeneratorMode)} className={inputClass()}>{MODES.map(mode=><option value={mode} key={mode}>{t(`modes.${mode}`)}</option>)}</select><GeneratorFields settings={settings} t={t} numeric={numeric} toggleList={toggleList}/></div>:<div className="mt-6"><label htmlFor="cron-direct" className="font-bold">{t("direct.label")}</label><p id="cron-direct-help" className="mt-1 text-sm text-[var(--text-muted)]">{t("direct.help")}</p><input id="cron-direct" aria-describedby="cron-direct-help" value={expression} onChange={e=>directChange(e.target.value)} spellCheck={false} className={`${inputClass()} mt-3 font-mono`} /></div>}
  </section>
  <section className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5 shadow-sm sm:p-6" aria-labelledby="cron-result-title"><h2 id="cron-result-title" className="text-xl font-bold">{t("result.title")}</h2><div className="mt-4 flex min-w-0 flex-col gap-3 sm:flex-row"><code className="min-h-12 min-w-0 flex-1 overflow-x-auto rounded-xl bg-[var(--code-bg)] p-3 text-base text-white">{expression||t("result.empty")}</code><Button onClick={()=>copy("cron",expression)} disabled={!result.valid}><Clipboard size={17} aria-hidden="true"/>{copied==="cron"?t("actions.copied"):t("actions.copyCron")}</Button></div>
   {result.valid?<div className="mt-4 space-y-4"><p role="status" className="flex items-center gap-2 font-semibold text-[var(--success-fg)]"><Check size={18} aria-hidden="true"/>{t("status.valid")}</p><div className="rounded-xl bg-[var(--info-bg)] p-4"><h3 className="font-bold">{t("descriptionTitle")}</h3><p className="mt-1 leading-7">{description}</p><button onClick={()=>copy("description",description)} className="mt-2 min-h-11 font-semibold text-[var(--primary)]">{copied==="description"?t("actions.copied"):t("actions.copyDescription")}</button></div>{result.domDowOr?<p role="alert" className="rounded-xl bg-[var(--warning-bg)] p-4 text-sm font-semibold text-[var(--warning-fg)]">{t("warnings.domDowOr")}</p>:null}<FieldBreakdown fields={result.fields} t={t}/></div>:error?<p role="alert" className="mt-4 rounded-xl bg-[var(--error-bg)] p-4 font-semibold text-[var(--error-fg)]">{error}</p>:<p className="mt-4 text-[var(--text-muted)]">{t("status.empty")}</p>}
   {copyError?<p role="alert" className="mt-3 text-sm font-semibold text-[var(--error-fg)]">{t("errors.copy")}</p>:null}
  </section>
  <section className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5 shadow-sm sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><label htmlFor="cron-timezone" className="font-bold">{t("timezone.label")}</label><select id="cron-timezone" value={zone} onChange={e=>setZone(e.target.value)} className={`${inputClass()} mt-2`}><option value={browserZone}>{t("timezone.browser",{zone:browserZone})}</option>{browserZone!=="UTC"?<option value="UTC">UTC</option>:null}{browserZone!=="Asia/Seoul"?<option value="Asia/Seoul">Asia/Seoul</option>:null}</select></div><div><label htmlFor="cron-count" className="font-bold">{t("next.count")}</label><select id="cron-count" value={count} onChange={e=>setCount(Number(e.target.value))} className={`${inputClass()} mt-2`}>{[5,10,20].map(value=><option key={value} value={value}>{value}</option>)}</select></div></div><p className="mt-4 rounded-xl bg-[var(--warning-bg)] p-4 text-sm text-[var(--warning-fg)]">{t("timezone.warning")}</p><h2 className="mt-5 text-xl font-bold">{t("next.title")}</h2>{result.valid&&runs.length?<ol className="mt-3 grid gap-2 sm:grid-cols-2">{runs.map((run,index)=><li key={run.toISOString()} className="rounded-xl bg-[var(--surface-muted)] p-3"><span className="mr-2 font-bold text-[var(--text-muted)]">{index+1}.</span><time dateTime={run.toISOString()}>{formatRun(run,zone,locale)}</time></li>)}</ol>:<p className="mt-3 text-[var(--text-muted)]">{t("next.empty")}</p>}</section>
  <div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={clear}><RotateCcw size={17} aria-hidden="true"/>{t("actions.clear")}</Button></div>
 </div>}

function GeneratorFields({settings,t,numeric,toggleList}:{settings:GeneratorSettings;t:ReturnType<typeof useTranslations>;numeric:(key:"minute"|"hour"|"interval",raw:string,min:number,max:number)=>void;toggleList:(key:"days"|"months"|"dates",value:number)=>void}){const needsTime=["hourly","every-n-hours","daily","weekly","monthly","specific-date"].includes(settings.mode);return <div className="grid gap-5">{["every-n-minutes","every-n-hours"].includes(settings.mode)?<NumberField id="cron-interval" label={t("generator.interval")} value={settings.interval} min={1} max={settings.mode==="every-n-minutes"?59:23} onChange={v=>numeric("interval",v,1,settings.mode==="every-n-minutes"?59:23)}/>:null}{needsTime?<div className="grid grid-cols-2 gap-3"><NumberField id="cron-hour" label={t("generator.hour")} value={settings.hour} min={0} max={23} onChange={v=>numeric("hour",v,0,23)}/><NumberField id="cron-minute" label={t("generator.minute")} value={settings.minute} min={0} max={59} onChange={v=>numeric("minute",v,0,59)}/></div>:null}{["weekly"].includes(settings.mode)?<ToggleGroup title={t("generator.weekdays")} values={WEEKDAYS} selected={settings.days} label={v=>t(`weekdays.${v}`)} toggle={v=>toggleList("days",v)}/>:null}{["monthly","specific-date"].includes(settings.mode)?<ToggleGroup title={t("generator.dates")} values={DATES} selected={settings.dates} label={String} toggle={v=>toggleList("dates",v)}/>:null}{settings.mode==="specific-date"?<ToggleGroup title={t("generator.months")} values={MONTHS} selected={settings.months} label={v=>t("generator.monthLabel",{month:v})} toggle={v=>toggleList("months",v)}/>:null}</div>}
function NumberField({id,label,value,min,max,onChange}:{id:string;label:string;value:number;min:number;max:number;onChange:(value:string)=>void}){return <label htmlFor={id} className="block font-semibold">{label}<input id={id} type="number" value={value} min={min} max={max} onChange={e=>onChange(e.target.value)} className={`${inputClass()} mt-2`}/></label>}
function ToggleGroup({title,values,selected,label,toggle}:{title:string;values:number[];selected:number[];label:(value:number)=>string;toggle:(value:number)=>void}){return <fieldset><legend className="font-bold">{title}</legend><div className="mt-2 flex flex-wrap gap-2">{values.map(value=><button key={value} type="button" aria-pressed={selected.includes(value)} onClick={()=>toggle(value)} className={`min-h-11 min-w-11 rounded-xl border px-3 py-2 text-sm font-semibold ${selected.includes(value)?"border-[var(--primary)] bg-[var(--primary-fill)] text-white":"border-[var(--border)] bg-[var(--surface)] hover:bg-[var(--surface-muted)]"}`}>{label(value)}</button>)}</div></fieldset>}
function FieldBreakdown({fields,t}:{fields:Record<string,string>;t:ReturnType<typeof useTranslations>}){return <div><h3 className="font-bold">{t("fields.title")}</h3><dl className="mt-3 grid gap-2 sm:grid-cols-5">{FIELD_DEFINITIONS.map(field=><div key={field.key} className="min-w-0 rounded-xl border border-[var(--border)] p-3"><dt className="text-xs font-bold text-[var(--text-muted)]">{t(`fields.${field.key}`)}</dt><dd className="mt-1 overflow-x-auto font-mono font-bold">{fields[field.key]}</dd><dd className="mt-1 text-xs text-[var(--text-muted)]">{field.min}–{field.max}</dd></div>)}</dl></div>}
function formatError(error:CronError|undefined,t:ReturnType<typeof useTranslations>):string{if(!error)return t("errors.syntax");if(error.code==="field-count")return t("errors.fieldCount");if(error.code==="too-long")return t("errors.tooLong");const field=error.field?t(`fields.${error.field}`):"",token=error.token??"",min=error.min??0,max=error.max??0;if(error.code==="range")return t("errors.range",{field,min,max,token});if(error.code==="range-order")return t("errors.rangeOrder",{field,token});if(error.code==="step")return t("errors.step",{field,min,max,token});return t("errors.syntaxToken",{field,token})}
function inputClass(){return"min-h-12 w-full rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 py-2 focus:outline-none focus:ring-4 focus:ring-[var(--focus-ring)]"}function tabClass(active:boolean){return`min-h-11 rounded-lg px-3 py-2 font-bold ${active?"bg-[var(--surface)] text-[var(--primary)] shadow-sm":"text-[var(--text-muted)] hover:text-[var(--foreground)]"}`}
