import type { Metadata } from "next";
import { hasLocale } from "next-intl";
import { getTranslations, setRequestLocale } from "next-intl/server";
import { notFound } from "next/navigation";
import { Container } from "@/components/layout/container";
import { ImageColorPicker, type ImageColorPickerLabels } from "@/components/tools/image-color-picker/image-color-picker";
import { routing } from "@/i18n/routing";
import { createPageMetadata } from "@/lib/seo";
type PageProps={params:Promise<{locale:string}>};
export async function generateMetadata({params}:PageProps):Promise<Metadata>{const{locale}=await params;if(!hasLocale(routing.locales,locale))notFound();const t=await getTranslations({locale,namespace:"Tools.imageColorPicker.metadata"});const pathname=`/${locale}/tools/image-color-picker`;return createPageMetadata({locale,title:t("title"),description:t("description"),pathname})}
export default async function Page({params}:PageProps){const{locale}=await params;if(!hasLocale(routing.locales,locale))notFound();setRequestLocale(locale);const t=await getTranslations("Tools.imageColorPicker");
 const labels:ImageColorPickerLabels={uploadTitle:t("upload.title"),uploadHelp:t("upload.help"),choose:t("actions.choose"),drop:t("upload.drop"),change:t("actions.change"),reset:t("actions.reset"),loading:t("status.loading"),imageInfo:t("info.title"),fileName:t("info.name"),format:t("info.format"),dimensions:t("info.dimensions"),fileSize:t("info.size"),zoom:t("zoom.label"),fit:t("zoom.fit"),preview:t("preview.title"),previewAlt:t("preview.alt"),selectHelp:t("preview.help"),coordinateTitle:t("coordinates.title"),x:t("coordinates.x"),y:t("coordinates.y"),selectCoordinate:t("coordinates.select"),selected:t("result.title"),noSelection:t("result.empty"),history:t("history.title"),historyEmpty:t("history.empty"),copy:t("actions.copy"),copied:t("actions.copied"),formats:{hex:t("formats.hex"),rgb:t("formats.rgb"),hsl:t("formats.hsl"),hsv:t("formats.hsv"),cmyk:t("formats.cmyk")},errors:{"multiple-files":t("errors.multiple"),"unsupported-type":t("errors.unsupported"),"signature-mismatch":t("errors.signature"),"file-too-large":t("errors.fileLarge"),"image-too-large":t("errors.imageLarge"),"decode-failed":t("errors.decode"),"pixel-read-failed":t("errors.pixel"),"coordinate-invalid":t("errors.coordinate"),"clipboard-failed":t("errors.copy")},privacy:t("privacy.notice")};
 return <><section className="border-b border-[var(--border)] bg-[var(--surface)]"><Container className="py-10 sm:py-14"><div className="max-w-3xl"><h1 className="text-3xl font-bold tracking-tight text-[var(--foreground)] sm:text-5xl">{t("title")}</h1><p className="mt-4 text-lg leading-8 text-[var(--text-muted)]">{t("description")}</p></div></Container></section><Container className="py-8 sm:py-12"><ImageColorPicker labels={labels}/><section className="mt-8 grid gap-4 md:grid-cols-2"><Info title={t("guide.pixelTitle")} text={t("guide.pixelText")}/><Info title={t("guide.zoomTitle")} text={t("guide.zoomText")}/><Info title={t("guide.colorTitle")} text={t("guide.colorText")}/><Info title={t("privacy.title")} text={t("privacy.text")} blue/></section></Container></>}
function Info({title,text,blue=false}:{title:string;text:string;blue?:boolean}){return <div className={`rounded-2xl border p-5 sm:p-6 ${blue?"border-[var(--info-border)] bg-[var(--info-bg)]":"border-[var(--border)] bg-[var(--surface)]"}`}><h2 className={`font-bold ${blue?"text-[var(--info-fg)]":"text-[var(--foreground)]"}`}>{title}</h2><p className={`mt-2 text-sm leading-6 ${blue?"text-[var(--info-fg)]":"text-[var(--text-muted)]"}`}>{text}</p></div>}
