import type { TransferState } from "./model";

export type TransferEvent =
  | "SELECT_FILE" | "CREATE_SESSION" | "SESSION_CREATED" | "RECEIVER_JOINED" | "APPROVE"
  | "CONNECTED" | "META_SENT" | "RECEIVER_ACCEPTED" | "START" | "END_RECEIVED"
  | "COMPLETE_ACK" | "FAIL" | "CANCEL" | "EXPIRE" | "RESET" | "RETRY";

const transitions: Partial<Record<TransferState, Partial<Record<TransferEvent, TransferState>>>> = {
  IDLE: { SELECT_FILE: "FILE_SELECTED", FAIL: "FAILED" },
  FILE_SELECTED: { CREATE_SESSION: "SESSION_CREATING", CANCEL: "CANCELLED", FAIL: "FAILED", RESET: "IDLE" },
  SESSION_CREATING: { SESSION_CREATED: "WAITING_FOR_RECEIVER", CANCEL: "CANCELLED", FAIL: "FAILED" },
  WAITING_FOR_RECEIVER: { RECEIVER_JOINED: "RECEIVER_JOINED", CANCEL: "CANCELLED", EXPIRE: "EXPIRED", FAIL: "FAILED" },
  RECEIVER_JOINED: { APPROVE: "NEGOTIATING", CANCEL: "CANCELLED", FAIL: "FAILED" },
  NEGOTIATING: { CONNECTED: "CONNECTED", CANCEL: "CANCELLED", FAIL: "FAILED" },
  CONNECTED: { META_SENT: "WAITING_RECEIVER_ACCEPT", CANCEL: "CANCELLED", FAIL: "FAILED" },
  WAITING_RECEIVER_ACCEPT: { RECEIVER_ACCEPTED: "READY", CANCEL: "CANCELLED", FAIL: "FAILED" },
  READY: { START: "TRANSFERRING", CANCEL: "CANCELLED", FAIL: "FAILED" },
  TRANSFERRING: { END_RECEIVED: "VERIFYING", CANCEL: "CANCELLED", FAIL: "FAILED" },
  VERIFYING: { COMPLETE_ACK: "COMPLETED", CANCEL: "CANCELLED", FAIL: "FAILED" },
  COMPLETED: { RESET: "IDLE" }, FAILED: { RETRY: "FILE_SELECTED", RESET: "IDLE" },
  CANCELLED: { RESET: "IDLE" }, EXPIRED: { RESET: "IDLE" },
};

export function transition(state: TransferState, event: TransferEvent): TransferState {
  return transitions[state]?.[event] ?? state;
}

export function shouldWarnBeforeUnload(state: TransferState): boolean {
  return ["NEGOTIATING", "CONNECTED", "WAITING_RECEIVER_ACCEPT", "READY", "TRANSFERRING", "VERIFYING"].includes(state);
}
